INSERT INTO CATEGORY (description) VALUES ('AMERICAN');
INSERT INTO CATEGORY (description) VALUES ('Italian');
INSERT INTO CATEGORY (description) VALUES ('Mexican');
INSERT INTO CATEGORY (description) VALUES ('Fast Food');
INSERT INTO UNIT_OF_MEASURE (uom) VALUES ('TeaSpoon');
INSERT INTO UNIT_OF_MEASURE (uom) VALUES ('TableSpoon');
INSERT INTO UNIT_OF_MEASURE (uom) VALUES ('Cup');
INSERT INTO UNIT_OF_MEASURE (uom) VALUES ('Pinch');
INSERT INTO UNIT_OF_MEASURE (uom) VALUES ('Grams');